### ISSUE TITLE
Automatically update data.

### ISSUE THREAD

**Issue by xivk** [anyways-open/cycling-backend#8]
Setup a process that automatically updates the OSM data. Make sure to include #3 by adding elevation data to the routerdb being constructed.

**Comment by pietervdvn** [comment]
0 0 * * * cd /var/data/mapdata && ./update-map.sh >> map_update_log_last.txt

Map update runs every night

**Comment by pietervdvn** [comment]
Don't know about the elevation data though, what flags and data should be used for that?

**Comment by xivk** [comment]
This is in the examples:

https://github.com/itinero/idp#a-few-examples

Just add the --elevation flag and it should automagically download SRTM data and add it to the routerdb.

**Comment by xivk** [comment]
How to do this:

- Add a build to https://build.anyways.eu/
- Push the docker image to docker hub (we have an account).
- Update the docker image when there is a newer latest available.

**Comment by xivk** [comment]
This one is an example where a docker container is built and pushed:

https://build.anyways.eu/viewType.html?buildTypeId=anyways_ViaOsmService_ViaOsmService

**Comment by pietervdvn** [comment]
I guess the previous comments should have gone into #7? I've pasted them there.

`--elevation` has been added, do you close the issue after review?

**Comment by xivk** [comment]
There is no elevation yet in the responses from the backend.

**Comment by pietervdvn** [comment]
I did a deep dive into the code. The FileMonitoring was overly complicated with lots of code duplication.

I've cleaned that up, added logging (so that we know for sure when reloading happens) and added a first unit test to test reloading.

Furthermore, when running locally with the latest routerdb, I do see three values on returned coordinates, so I suspect that this is elevation:

   |  
-- | --
0 | 5.48869
1 | 50.96598
2 | 64

I strongly suspect that automatic reloading was broken in production (although I can't prove that).
Normally, this issue should be fixed once the new version is deployed.
